### PR TITLE
Allow for start offset on panning, to prevent jumps when panning star…

### PR DESCRIPTION
**Pull request by fede-s**
…ts on Android 12

### CODE REVIEW

**Comment by fede-s** [comment]
Fix for issue #16

**Comment by kesha-antonov** [comment]
Thanks!

**Comment by kesha-antonov** [comment]
Hi

Seems like this PR introduced bug. At least on iOS devices

With this PR:

https://github.com/kesha-antonov/react-native-zoom-reanimated/assets/11584712/4fe0bb12-56dc-49ad-ac66-331270caa8da

Without:

https://github.com/kesha-antonov/react-native-zoom-reanimated/assets/11584712/6feb0588-1dd4-4961-8cbe-ebc661bf2717

**Comment by kesha-antonov** [comment]
Fixed in new version

https://www.npmjs.com/package/react-native-zoom-reanimated?activeTab=versions

**Pull request merged**
